import Head from "next/head";
import { useRef, useState } from "react";
import styled from "styled-components";

export default function Home() {
  const inputRef = useRef();
  const [shortUrl, setShortUrl] = useState(null);

  const handleSubmit = (e) => {
    e.preventDefault();
    const url = inputRef.current.value;

    fetch("/api/shortUrl", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ url }),
    })
      .then((res) => res.json())
      .then((data) => {
        setShortUrl(data.shortUrl);
      })
      .catch((err) => console.log(err.response));
  };

  return (
    <Container>
      <Head>
        <title>URL - Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ShortUrl>
        <Title>
          <h1>URL - Shortener</h1>
        </Title>
        <Form onSubmit={handleSubmit}>
          <input type="text" placeholder="URL" ref={inputRef} />
          <button type="submit">Acortar URL</button>
        </Form>
        <Url>
          <span>{shortUrl && shortUrl}</span>
        </Url>
      </ShortUrl>
    </Container>
  );
}

const Container = styled.div`
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
`;

const ShortUrl = styled.div``;

const Title = styled.div`
  margin-bottom: 10px;
  text-align: center;

  h1 {
    font-size: 40px;
  }
`;

const Form = styled.form`
  min-width: 500px;

  input {
    width: 100%;
    padding: 10px;
    margin-bottom: 10px;

    &:focus {
      outline: none;
    }
  }

  button {
    width: 100%;
    padding: 10px;
    border: none;
    transition: 0.3s ease-in-out;
    font-weight: bold;

    &:hover {
      cursor: pointer;
      background-color: black;
      color: white;
    }
  }
`;

const Url = styled.div`
  span {
    font-size: 20px;
  }
`;
